/**
 * Well-known TRC20 token metadata (mainnet).
 *
 * Auto-generated by scripts/update-trc20-tokens.ts
 * Generated at: 2026-06-06T17:51:12.688Z
 *
 * To add more tokens:
 *   npm run update-trc20-tokens <address1> <address2> ...
 */
export const COMMON_TRC20_TOKENS: Record<
  string,
  { symbol: string; name: string; decimals: number }
> = {
  'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t': { symbol: 'USDT', name: 'Tether USD', decimals: 6 },
};
