#!/usr/bin/env node
/**
 * Fetch TRC20 token metadata from TRON Grid API and update the common tokens file.
 *
 * Usage:
 *   npx tsx scripts/update-trc20-tokens.ts                    # Fetch defaults
 *   npx tsx scripts/update-trc20-tokens.ts <addr1> <addr2>    # Fetch specific
 *
 * Add well-known token addresses to DEFAULT_ADDRESSES below so the whole team
 * benefits without passing CLI arguments each time.
 */

import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const TRON_GRID = 'https://api.trongrid.io';

// ---------------------------------------------------------------------------
// Update this list when new well-known TRC20 tokens should be included
// ---------------------------------------------------------------------------
const DEFAULT_ADDRESSES: string[] = [
  'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t', // USDT
  // Add more addresses here (case-sensitive, base58 format)
];

// ---------------------------------------------------------------------------
// Minimal ABI decoding (must match src/providers/tron.ts)
// ---------------------------------------------------------------------------

function abiDecodeUint256(hex: string): number {
  const clean = hex.replace('0x', '').padStart(64, '0');
  return parseInt(clean.slice(-64), 16);
}

function abiDecodeString(hex: string): string {
  const clean = hex.replace('0x', '');
  if (clean.length < 128) return '';
  const offset = parseInt(clean.substring(0, 64), 16) * 2;
  const length = parseInt(clean.substring(offset, offset + 64), 16);
  const start = offset + 64;
  const end = Math.min(start + length * 2, clean.length);
  let str = '';
  for (let i = start; i < end; i += 2) {
    const code = parseInt(clean.substring(i, i + 2), 16);
    if (code === 0) break;
    str += String.fromCharCode(code);
  }
  return str;
}

// ---------------------------------------------------------------------------
// TRON base58 → hex conversion
// ---------------------------------------------------------------------------
const BASE58_ALPHABET = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';

function base58ToHex(base58: string): string {
  let num = 0n;
  for (const c of base58) {
    num = num * 58n + BigInt(BASE58_ALPHABET.indexOf(c));
  }
  let hex = num.toString(16);
  if (hex.length % 2 !== 0) hex = '0' + hex;
  return hex.slice(0, hex.length - 8); // strip 4-byte checksum
}

// ---------------------------------------------------------------------------
// TRON Grid API call
// ---------------------------------------------------------------------------

async function callContract(
  contractAddress: string,
  functionSelector: string,
): Promise<string> {
  const res = await fetch(`${TRON_GRID}/wallet/triggerconstantcontract`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      owner_address: '410000000000000000000000000000000000000000',
      contract_address: base58ToHex(contractAddress),
      function_selector: functionSelector,
      parameter: '',
    }),
    signal: AbortSignal.timeout(10_000),
  });

  if (!res.ok) {
    throw new Error(`HTTP ${res.status}`);
  }

  const json = (await res.json()) as {
    result?: { result?: boolean };
    constant_result?: string[];
  };

  if (!json.result?.result) {
    throw new Error('contract call failed');
  }

  return json.constant_result?.[0] ?? '';
}

async function fetchTokenMeta(
  address: string,
): Promise<{ symbol: string; name: string; decimals: number } | null> {
  const [symbolHex, nameHex, decimalsHex] = await Promise.all([
    callContract(address, 'symbol()'),
    callContract(address, 'name()'),
    callContract(address, 'decimals()'),
  ]);

  const symbol = abiDecodeString(symbolHex);
  const name = abiDecodeString(nameHex);
  const decimals = abiDecodeUint256(decimalsHex);

  if (!symbol) {
    throw new Error(`empty symbol — maybe not a TRC20 token?`);
  }

  return { symbol, name, decimals };
}

// ---------------------------------------------------------------------------
// TS file generation
// ---------------------------------------------------------------------------

function generateTsFile(
  entries: Record<string, { symbol: string; name: string; decimals: number }>,
  failed: string[],
): string {
  const lines: string[] = [
    '/**',
    ' * Well-known TRC20 token metadata (mainnet).',
    ' *',
    ' * Auto-generated by scripts/update-trc20-tokens.ts',
    ` * Generated at: ${new Date().toISOString()}`,
    ' *',
    ' * To add more tokens:',
    ' *   npm run update-trc20-tokens <address1> <address2> ...',
    ' */',
    'export const COMMON_TRC20_TOKENS: Record<',
    '  string,',
    '  { symbol: string; name: string; decimals: number }',
    '> = {',
  ];

  const sorted = Object.entries(entries).sort(([a], [b]) =>
    a.toLowerCase().localeCompare(b.toLowerCase()),
  );

  for (const [address, meta] of sorted) {
    const comment = failed.includes(address) ? ' // fetch failed, using cached value' : '';
    lines.push(`  '${address}': { symbol: '${meta.symbol}', name: '${meta.name}', decimals: ${meta.decimals} },${comment}`);
  }

  lines.push('};');
  lines.push('');

  if (failed.length > 0) {
    const warn = failed
      .filter((a) => entries[a])
      .map((a) => `  // ${a}: fetch failed, previous value preserved`);
    if (warn.length > 0) {
      lines.push('// Tokens that failed to fetch (previous values kept):');
      lines.push(...warn);
    }
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  const addresses =
    process.argv.length > 2 ? process.argv.slice(2) : DEFAULT_ADDRESSES;

  console.log(`Fetching metadata for ${addresses.length} TRC20 token(s)...\n`);

  // Try to read existing entries to preserve them on failure
  const existingPath = resolve(
    __dirname,
    '..',
    'src/providers/tron-common-tokens.ts',
  );
  let existing: Record<string, { symbol: string; name: string; decimals: number }> = {};
  try {
    const fs = await import('fs');
    const content = fs.readFileSync(existingPath, 'utf-8');
    const match = content.match(/COMMON_TRC20_TOKENS:\s*Record<[\s\S]*?> = ([\s\S]*?);/);
    if (match) {
      existing = JSON.parse(
        match[1]
          .replace(/(\w+):/g, '"$1":')
          .replace(/'/g, '"')
          .replace(/\/\/.*$/gm, '')
          .replace(/,\s*}/g, '}'),
      );
    }
  } catch {
    // File doesn't exist or can't be parsed — start fresh
  }

  const results: Record<string, { symbol: string; name: string; decimals: number }> = {
    ...existing,
  };
  const failed: string[] = [];

  for (const addr of addresses) {
    try {
      const meta = await fetchTokenMeta(addr);
      if (meta) {
        results[addr] = meta;
        console.log(`  ✓ ${addr}: ${meta.symbol} (${meta.name}, ${meta.decimals} decimals)`);
      }
    } catch (err) {
      // Keep existing entry if available
      if (existing[addr]) {
        failed.push(addr);
        console.log(`  ✗ ${addr}: ${(err as Error).message} (kept existing)`);
      } else {
        console.log(`  ✗ ${addr}: ${(err as Error).message} (skipped)`);
      }
    }
  }

  const content = generateTsFile(results, failed);
  writeFileSync(existingPath, content, 'utf-8');

  const total = Object.keys(results).length;
  const newCount = addresses.filter((a) => !existing[a] && results[a]).length;
  console.log(`\nDone. ${total} token(s) in file (${newCount} new).`);
  console.log(`File: ${existingPath}`);
}

main().catch((err) => {
  console.error('Fatal:', err);
  process.exit(1);
});
